from __future__ import annotations

from pathlib import Path


CONTROL_CODES = {
    0x00: "END",
    0x01: "TEXTBOX_BREAK",
    0x02: "MESSAGE_END",
    0x03: "LINE_BREAK",
    0x05: "PAUSE",
    0x07: "PAUSE_OR_SOUND",
    0x08: "ICON",
    0x1E: "YES_NO_PROMPT",
}


def glyph_char_for_code(code: int, encoding: str) -> str:
    if 0x20 <= code <= 0x7E:
        return chr(code)
    try:
        char = bytes([code]).decode(encoding)
    except UnicodeDecodeError:
        char = f"<UNMAPPED_{code:02X}>"
    return char if char.isprintable() else f"<CTRL_{code:02X}>"


def build_table_lines(encoding: str, note: str, start: int = 0x00, end: int = 0xFF) -> list[str]:
    lines = [
        "# Auto-generated candidate table.",
        f"# {note}",
        f"# Encoding assumption for printable glyph codes: {encoding}",
        "# This file is generated by Stage 1 and must be validated in Stage 2.",
        "",
    ]
    for code in range(start, end + 1):
        if code in CONTROL_CODES:
            lines.append(f"{code:02X}=<{CONTROL_CODES[code]}>")
        elif code < 0x20:
            continue
        else:
            lines.append(f"{code:02X}={glyph_char_for_code(code, encoding)}")
    return lines


def write_candidate_tbl(path: Path, encoding: str, note: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(build_table_lines(encoding, note)) + "\n", encoding="utf-8")


def decode_bytes(raw: bytes, encoding: str) -> str:
    out: list[str] = []
    for b in raw:
        if b == 0:
            break
        if b in CONTROL_CODES and b != 0:
            out.append(f"[{CONTROL_CODES[b]}]")
        else:
            out.append(glyph_char_for_code(b, encoding))
    return "".join(out)

